const config = {
  basename: import.meta.env.VITE_BASE_NAME!,
  baseURI: import.meta.env.VITE_API_BASE_URI!,
  endpoints: {
    auth: {
      login: "auth/v1/account/login/",
      logout: "auth/v1/account/logout/",
      refresh: "/auth/v1/token/access/",
    },
    api: {
      user: {
        list: "api/v1/user/list/",
        create: "api/v1/user/create/",
        update: id => `api/v1/user/update/${id}/`,
        delete: id => `api/v1/user/toggle-status/${id}/`,
        globalSearch: "api/v1/admin/search/",
      },
      security: {
        update: id => `api/v1/user/change-password/${id}/`,
      },
      role: {
        list: "api/v1/role/list/",
        catPerms: "api/v1/category/permissions/",
        assign: id => `api/v1/user/assign-permissions/${id}/`,
        rolePerms: (roleId: string) => `api/v1/role/permissions/${roleId}/`,
      },
      school: {
        list: "api/v1/school/list/",
        create: "api/v1/school/create/",
        basicUpdate: id => `api/v1/school/update/${id}/`,
        addressUpdate: id => `api/v1/school/address/update/${id}/`,
        contactUpdate: id => `api/v1/school/contact/update/${id}/`,
        featureUpdate: id => `api/v1/school/feature/update/${id}/`,
        toggleStatus: id => `api/v1/school/toggle-visibility/${id}/`,
        assignCourse: "api/v1/school/assign-course/",
        unassignCourse: "api/v1/school/unassign-course/",
        courseList: id => `api/v1/school/courses/${id}/`,
        globalSearch: "api/v1/admin/search/",
      },
      course: {
        list: "api/v1/course/list/",
        listbyIsOptional:isOptional=> `api/v1/course/list/?isOptional=${isOptional}`,
        listUnitTableofContent: courseId => `api/v1/course/detail/${courseId}/`,
        levelList: "/api/v1/level/list/",
        listByGrade: gradeId => `api/v1/grade/courses/${gradeId}/`,
        listByUnit: unitId => `api/v1/course/units/${unitId}/`,
        listByCareer: careerId => `api/v1/career/courses/${careerId}/`,
        create: "api/v1/course/create/",
        update: id => `api/v1/course/update/${id}/`,
        delete: id => `api/v1/course/delete/${id}/`,
        assignUnit: "api/v1/course/assign-units/",
        unassignUnit: "api/v1/course/unassign-units/",
        approveCourse: id => `api/v1/course/approve/${id}/`,
      },
      unit: {
        list: "api/v1/unit/list/",
        listByCourse: courseId => `api/v1/course/units/${courseId}`,
        create: "api/v1/unit/create/",
        update: id => `api/v1/unit/update/${id}`,
        delete: id => `api/v1/unit/delete/${id}`,
        assignSkill: "api/v1/unit/assign-skills/",
        unassignSkill: "api/v1/unit/unassign-skills/",
        skillList: unitId => `api/v1/unit/skills/${unitId}/`,
        updatePosition: "api/v1/unit/update-skill-position/",
      },
      grade: {
        list: "api/v1/grade/list/",
        create: "api/v1/grade/create/",
        update: id => `api/v1/grade/update/${id}/`,
        delete: id => `api/v1/grade/delete/${id}/`,
        assignCareer: "api/v1/grade/assign-career/",
        assignCourse: "api/v1/grade/assign-courses/",
        unassignCourse: "api/v1/grade/unassign-courses/",
      },
      gradeCategory: {
        list: "api/v1/grade-category/list/",
        create: "api/v1/grade-category/create/",
        update: id => `api/v1/grade-category/update/${id}/`,
        delete: id => `api/v1/grade-category/delete/${id}/`,
        assignCareer: "api/v1/grade-category/assign-career/",
        assignCourse: "api/v1/grade-category/assign-courses/",
        unassignCourse: "api/v1/grade-category/unassign-courses/",
      },
      level: {
        list: "api/v1/level/list/",
        create: "api/v1/level/create/",
        update: id => `api/v1/level/update/${id}/`,
        delete: id => `api/v1/level/delete/${id}/`,
      },
      levelCategory: {
        list: "api/v1/level-type/list/",
        create: "api/v1/level-type/create/",
        update: id => `api/v1/level-type/update/${id}/`,
        delete: id => `api/v1/level-type/delete/${id}/`,
      },
      career: {
        list: "api/v1/career/list/",
        careerByGrade: id => `api/v1/grade/careers/${id}/`,
        listByCourse: courseId => `api/v1/career/courses/${courseId}/`,
        create: "api/v1/career/create/",
        update: id => `api/v1/career/update/${id}/`,
        delete: id => `api/v1/career/delete/${id}/`,
        assignCourse: "api/v1/career/assign-courses/",
        unassignCareer: "api/v1/grade/unassign-career/",
        unassignCourses: "api/v1/career/unassign-courses/",
      },
      skill: {
        list: "api/v1/skill/list/",
        listByUnit: unitId => `api/v1/unit/skills/${unitId}/`,
        create: "api/v1/skill/create/",
        update: id => `api/v1/skill/update/${id}/`,
        delete: id => `api/v1/skill/delete/${id}/`,
        assignIndicator: "api/v1/skill/assign-indicators/",
        unassignIndicator: "api/v1/skill/unassign-indicators/",
        listByIndicator: indicatorId => `api/v1/skill/indicators/${indicatorId}/`,
        updatePosition: "api/v1/skill/update-indicator-position/",
      },
      indicator: {
        list: "api/v1/indicator/list/",
        listBySkill: skillId => `api/v1/skill/indicators/${skillId}/`,
        create: "api/v1/indicator/create/",
        update: id => `api/v1/indicator/update/${id}/`,
        delete: `api/v1/indicator/delete`,
        assignLesson: "api/v1/indicator/assign-lessons/",
        listByLesson: id => `api/v1/indicator/lessons/${id}/`,
        unassignLesson: "api/v1/indicator/unassign-lessons/",
        updatePosition: "api/v1/indicator/update-lesson-position/",
      },
      lesson: {
        list: "api/v1/lesson/list/",
        listByIndicator: id => `api/v1/indicator/lessons/${id}/`,
        listByContent: id => `api/v1/lesson/contents/${id}`,
        videoContent: id => `api/v1/content/details/${id}/`,
        create: "api/v1/lesson/create/",
        update: id => `api/v1/lesson/update/${id}/`,
        delete: id => `api/v1/lesson/delete/${id}/`,
        lessonPositionUpdate: "api/v1/lesson/update-content-position/",
        assignLesson: "api/v1/indicator/assign-lessons/",
      },
      content: {
        list: "api/v1/content/list/",
        search: "api/v1/content/search/",
        create: "api/v1/content/create/",
        update: id => `api/v1/content/update/${id}/`,
        delete: id => `api/v1/content/delete/${id}/`,
        details: id => `api/v1/content/details/${id}/`,
        bloomList: "api/v1/content/blooms-taxonomy-level/",
        abilityList: "api/v1/ability-category/list/",
        unassignContent: "api/v1/lesson/unassign-contents/",
      },
      quiz: {
        addOneQuestion: `api/v1/content/question/add`,
        questionUpdate: `api/v1/content/question/update`,
        questionDelete: (id: string) => `api/v1/content/question/delete/${id}/`,
        answerUpdate: `api/v1/content/answer/update`,
        answerDelete: (id: string) => `api/v1/content/answer/delete/${id}/`,
      },
      abilityCategory: {
        list: "api/v1/ability-category/list/",
        listById: (id: string) => `api/v1/ability-category/${id}/`,
        create: "api/v1/ability-category/create/",
        update: id => `api/v1/ability-category/update/${id}/`,
        delete: id => `api/v1/ability-category/delete/${id}/`,
      },
      events: {
        list: "api/v1/event/list/",
        create: "api/v1/event/create/",
        update: id => `api/v1/event/update/${id}/`,
        delete: id => `api/v1/event/delete/${id}/`,
      },
      assigned: {
        list: "api/v1/event/assigned/",
      },
      eventdetails: {
        details: id => `api/v1/event/detail/${id}/`,
      },
      basket: {
        list: "api/v1/basket/list/",
        details: (basketId: string) => `api/v1/basket/detail/${basketId}/`,
        create: "api/v1/basket/create/",
        addContentToExistingBasket: "api/v1/basket/add-content/",
        delete: id => `api/v1/basket/delete/${id}/`,
        update: id => `api/v1/basket/update/${id}/`,
        removeContentFromBasket: "api/v1/basket/remove-content/",
        assignToLesson: "api/v1/basket/assign-to-lesson/",
      },
      global: {
        search: "api/v1/search/global/",
      },
      file: {
        fileUpload: "api/v1/file/upload/",
      },
    },
  },
};

export default config;
