interface PATH_TYPE {
  DASHBOARD: string;
  LOGIN: string;
  STAFF: string;
  ADD_STAFF: string;
  PERMISSION: string;
  SCHOOL: string;
  ADD_SCHOOL: string;
  ASSIGNED_COURSES: string;
  ASSIGN_NEW_COURSES: string;
  UPDATE_SCHOOL: string;
  BASIC: string;
  ADDRESS: string;
  CONTACT: string;
  FEATURE: string;
  COURSE: string;
  UNIT: string;
  ADD_COURSE: string;
  ADD_UNIT: string;
  GRADE: string;
  ASSIGNED_CAREERS: string;
  ADD_GRADE: string;
  CAREER: string;
  ADD_CAREER: string;
  SKILL: string;
  ADD_SKILL: string;
  LESSON: string;
  ADD_LESSON: string;
  INDICATOR: string;
  ADD_INDICATOR: string;
  PROFILE: string;
  SETTING: string;
  SECURITY: string;
  CONTENT: string;
  CALENDAR: string;
  CONTENT_BASKET: string;
  TABLE_OF_CONTENT: string;
  ADD_CONTENT: string;
  ASSIGNED_UNITS: string;
  ASSIGNED_SKILLS: string;
  ASSIGNED_INDICATORS: string;
  ASSIGNED_LESSONS: string;
  LESSON_CARD: string;
  ABILITY: string;
  ADD_ABILITY_CATEGORY: string;
  // ALL_CONTENT_CARD: string;
  GRADE_CATEGORY: string;
  ADD_GRADE_CATEGORY: string;
  LEVEL_TYPE: string;
  ADD_LEVEL_TYPE: string;
}

export const PATH: PATH_TYPE = {
  DASHBOARD: "/",
  LOGIN: "login",
  STAFF: "staffs",
  ADD_STAFF: "addStaff",
  PERMISSION: "permission",
  SCHOOL: "schools",
  ADD_SCHOOL: "addschool",
  ASSIGNED_COURSES: "courses",
  ASSIGN_NEW_COURSES: "assigncourses",
  LESSON_CARD: "lesson-card",
  UPDATE_SCHOOL: "update",
  BASIC: "",
  ADDRESS: "address",
  CONTACT: "contact",
  FEATURE: "feature",
  COURSE: "courses",
  UNIT: "units",
  ASSIGNED_SKILLS: "skills",
  ADD_COURSE: "addcourse",
  ADD_UNIT: "addunit",
  ASSIGNED_UNITS: "units",
  GRADE: "grades",
  ADD_GRADE: "addgrade",
  CAREER: "careers",
  ADD_CAREER: "addcareer",
  ASSIGNED_CAREERS: "careers",
  SKILL: "skills",
  ADD_SKILL: "addskills",
  ASSIGNED_INDICATORS: "indicators",
  LESSON: "lessons",
  ADD_LESSON: "addlesson",
  INDICATOR: "indicators",
  ADD_INDICATOR: "addindicators",
  ASSIGNED_LESSONS: "lessons",
  PROFILE: "profile",
  SETTING: "setting",
  SECURITY: "security",
  CONTENT: "contents",
  CALENDAR: "calendar",
  TABLE_OF_CONTENT: "table-of-content",
  CONTENT_BASKET: "basket",
  ADD_CONTENT: "add-content",
  ABILITY: "ability-category",
  ADD_ABILITY_CATEGORY: "add-ability-category",
  GRADE_CATEGORY: "grade-category",
  ADD_GRADE_CATEGORY: "add-grade-category",
  LEVEL_TYPE: "level-type",
  ADD_LEVEL_TYPE: "add-level-type",
};
