name: Development Server Deploy
on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy User Dashboard on Development
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEVSERVERHOST }}
          username: ${{ secrets.DEVUSERNAME }}
          key: ${{ secrets.DEVPRIVATEKEY }}
          script: |
            cd /home/ubuntu/code/frontend
            export NVM_DIR=~/.nvm
            source "$NVM_DIR/nvm.sh" &&
            git checkout development &&
            git pull &&
            npm i &&
            npm run build &&
            pm2 reload ${{ secrets.DEVDEPLOYNAME }} &&
            echo "[+] DONE deploying the development server [+]"
