export const MorikiTableHeaderApiList = [
  'transaction_id',
  'invoice_date',
  'transaction_status_id',
  'transaction_status',
  'invoice_number',
  'invoice_view_number',
  'internal_code',
  'company_name',
  'company_employee_name',
  'customer_code',
  'customer_name',
  'employee_name_at_customer',
  'internal_item_id',
  'food_category_code',
  'food_category_1',
  'food_category_2',
  'food_category_3',
  'item_name',
  'item_standard',
  'package_qty',
  'package_qty_code',
  'package_qty_unit',
  'desired_unit_price',
  'desired_quantity',
  'desired_unit_code',
  'unit_code',
  'requested_amount',
  'unit_price',
  'quantity',
  'unit_code_char',
  'unit_code_amount',
  'amount',
  'tax_classification',
  'consumption_tax_subtotal',
  'subtotal',
  'my_catalog_id',
  'voucher_id',
  'item_tax_classification',
  'item_registration',
  'change_classification',
  'total_product_body',
  'total_item_consumption_tax',
  'total_shipping_fees',
  'total_shipping_consumption_tax',
  'total_other_total',
  'total',
  'order_date',
  'expected_shipping_date',
  'shipment_date',
  'delivery_date',
  'delivery_time',
  'temperature_range',
  'receipt_date',
  'subject',
  'voucher_control_number',
  'place_name_delivery',
  'delivery_location',
  'shipping_code',
  'delivery_carrier_name',
  'payment_agency',
  'payment_category',
  'price_quote_number',
  'quote_request_number',
  'quotation_number',
  'order_number',
  'order_number_secondary',
  'original_voucher_number',
  'site',
  'transmission_date',
  'order_sent',
  'update_date',
  'delivery_location_code',
  'company_unit_code',
  'quantity_unit_code',
  'jan_code_2',
  'ordering_comments',
];

export const SmileTableHeaderApiList: string[] = [
  'voucher_date',
  'customer_code',
  'customer_name1',
  'customer_name2',
  'item_code',
  'item_name',
  'sales_quantity',
  'quantity_unit',
  'kg_quantity',
  'unit_price',
  'amount',
  'aggregate_code',
  'order_no',
  'course_code',
  'course_name',
];

export const SmileCourseTableHeaderApiList: string[] = [
  'code',
  'fax_number',
  'text',
];

export const ProductTableHeaderApiList: string[] = [
  'code',
  'text',
  'sort_key',
  'supplier_code',
  'unit',
  'variety',
  'production_area',
  'partner',
  'partner_product_code',
  'size',
];
const a = [
  'Transaction ID',
  'Voucher date',
  'Transaction status code',
  'Transaction status',
  'Slip No.',
  'Invoice detail display order number',
  'In-house code',
  'Company member name',
  'In-house person in charge',
  'Customer code',
  'Customer name',
  'Contact person name',
  'In-house managed product code',
  'Food classification code',
  'Food major classification name',
  'Food medium classification name',
  'Food subclass name',
  'Product name',
  'standard',
  'Quantity',
  'unit code',
  'Quantity unit',
  'Requested unit price',
  'Requested quantity',
  'Desired unit code',
  'Preferred unit',
  'Requested amount',
  'unit price',
  'quantity',
  'Unit code',
  'unit',
  'Amount of money',
  'Tax classification',
  'consumption tax',
  'subtotal',
  'My Catalog ID',
  'Invoice detail ID',
  'Tax classification',
  'Product registration',
  'Change category',
  'Total product body',
  'Total product consumption tax',
  'total postage body',
  'Total Shipping Consumption Tax',
  'Total Other',
  'Total',
  'Order date',
  'Scheduled shipping date',
  'Date of shipment',
  'Delivery date',
  'Delivery time',
  'Temperature range',
  'Date of receipt',
  'subject',
  'Invoice control number',
  'Delivery location name',
  'delivery place address',
  'shipping code',
  'Logistics company name',
  'Payment agency use',
  'Payment type',
  'Quotation Proposal No.',
  'Request for Quotation No.',
  'Quotation No.',
  'Order No.',
  'Order No.',
  'Original slip No.',
  'site',
  'Sent date and time',
  'Date and time of order transmission',
  'update date',
  'Delivery location code',
  'Company unit code',
  'In-house company unit code',
  'JAN code 2',
  'Comment when ordering',
];

export const SmileCustomerTableHeaderApiList: string[] = [
  'code',
  'name',
  'course',
  'billing_code',
  'address',
  'telephone',
  'fax',
];
